### ISSUE TITLE
AxeResult throws exception if page being analysed uses prototype.js v1.6.1 script

### ISSUE THREAD

**Issue by swinslade** [TroyWalshProf/SeleniumAxeDotnet#102]
**Describe the bug**
Using Selenium.Axe v2.0.0 (and earlier version) on a page that is using prototype.js v1.6.1 script causes an exception to be thrown resulting in no output to be produced.

**To Reproduce**
Running the following on a page that uses prototype.js script (v1.6.1)

    `var result = new AxeBuilder(webDriver.SeleniumWebDriver).Analyze();`

causes an exception to be thrown at line 38 in _AxeResult.cs_ when it is executing the line 
    `Violations = violationsToken?.ToObject<AxeResultItem[]>();`

**Expected behavior**
Catch the exception or handle it some how (I'm not a developer so please excuse my presumption). I download the source code for the Selenium.Axe solution so I could put in a try/catch block around the code to see what it was reporting. I've attached the output
A look at the value of the result JObject shows that the json is not escaped properly. 
I suspect this is an issue with prototype.js v1.6.1 as I do not get the error if I swap it out and use v.1.7.3 (latest). 
However, as I am not the developer/owner of the page in question I have only been able to prove this by testing the page locally with these changes.

I am running this using
Selenium.Axe v 2.0.0
Chrome v86.0.4240.111
Selenium Webdriver v3.141.0
ChromeDriver v86
Windows 10 Enterprise, build 18363.1139

**Additional context**
I've attached the exception (Exception.txt) and the json value of the root (resultRoot.txt) from the **result** JObject variable (from line 29 in AxeResults.cs)
I've also attached an example page in PageTest.zip. Within this zip I have included both v1.6.1 and v1.7.3 of prototype.js and have added comments to the TestPage.html file (lines 18-22) so you can uncomment/switch between versions to see how this affects Selenium.Axe analysing the page:

[Exception.txt](https://github.com/TroyWalshProf/SeleniumAxeDotnet/files/5548787/Exception.txt)
[resultRoot.txt](https://github.com/TroyWalshProf/SeleniumAxeDotnet/files/5548788/resultRoot.txt)
[PageTest.zip](https://github.com/TroyWalshProf/SeleniumAxeDotnet/files/5548795/PageTest.zip)

Please let me know if I can provide any further information.

**Comment by TroyWalshProf** [comment]
This is an issue with the prototype framework completely overriding the browser Object toJSON functionality.

For more context please see: 
https://github.com/dequelabs/axe-core/issues/2657
https://github.com/TroyWalshProf/SeleniumAxeDotnet/pull/105#issuecomment-732344396
