### ISSUE TITLE
Add individual element images

### ISSUE THREAD

**Issue by TroyWalshProf** [TroyWalshProf/SeleniumAxeDotnet#112]
## Want to add element images to the HTML report.
Example:
![image](https://user-images.githubusercontent.com/2066107/101674967-c5639600-3a1e-11eb-9276-7c5457067330.png)

## Criteria 
1. HTML file needs to remain standalone - AKA any images would need to be imbedded
2. Would like to use the image from the CSS (https://github.com/TroyWalshProf/SeleniumAxeDotnet/blob/bd9da445437f7d2a00576a7de2980b89bffb4545/Selenium.Axe/Selenium.Axe/HtmlReport.cs#L209) so we don't bloat the HTML.
3. I am guessing we will need to run a secondary script in order to get the X Y coordinates and sizes for the element selectors.  We could then use those values to crop the images in the report something along these lines: https://stackoverflow.com/questions/493296/css-display-an-image-resized-and-cropped
4. Ideally would like to have some kind of hover over mechanism for these new image, kind of like this: https://www.w3schools.com/howto/howto_css_zoom_hover.asp

**Comment by jonreding2010** [comment]
@TroyWalshProf
I've begun working on this and have made some progress. The big question is where the image should be added and in what tag?
![Capture](https://user-images.githubusercontent.com/17068919/110040319-38bc3180-7d08-11eb-9a0c-81d4f8a7dc46.JPG)

**Comment by TroyWalshProf** [comment]
I would prefer if we used left/right alignment, see: https://css-tricks.com/left-and-right/
That being said I am fine with it being where you put it for now.  - Playing with the DIVs is the easy part.

**Comment by jonreding2010** [comment]
@TroyWalshProf I have a couple of questions going further:

1. which report types need to have the element image? (I have it going for passes and violations currently)
2. when messing with the drop downs, the element images don't disappear with it. Will the JS script in the beginning need to be edited as well?
3. I'm not able to get the images to load, have any ideas what I could be doing wrong?

Note: I have the GetImages method working but with normal loops. I will look into foreach but for now the method works properly.

Here's my fork that I'm working on: https://github.com/jonreding2010/SeleniumAxeDotnet

**Comment by TroyWalshProf** [comment]
@jonreding2010 

1. Passes and violations should be good.
2. Suggest embedding the images the say way we do the fullImage.  AKA we don't want to inject right into the HTML

Side notes* 
If possible we just want to crop the the fullImage to get the element images. 
Currently taking screenshots of elements will not if a event firing web driver is being used: https://github.com/SeleniumHQ/selenium/issues/9256

**Comment by jonreding2010** [comment]
Here is what the output looks like right now. There are still some formatting divs to be done and the snap shots are off a bit, but progress is being made
[5db8516d-0157-43c0-9bb2-958efd4f0692.zip](https://github.com/TroyWalshProf/SeleniumAxeDotnet/files/6327239/5db8516d-0157-43c0-9bb2-958efd4f0692.zip)

**Comment by TroyWalshProf** [comment]
You are 100% on the right track

**Comment by TroyWalshProf** [comment]
So I looked at this a bit more.
You are on track but we don't want to save multiple images, we just want to crop the one image we have.
See:
[SAMPLE.zip](https://github.com/TroyWalshProf/SeleniumAxeDotnet/files/6332002/SAMPLE.zip)

**Comment by TroyWalshProf** [comment]
This will be done in a different project, more coming soon
