### ISSUE TITLE
make iframe script injection optional

### ISSUE THREAD

**Issue by techtor** [TroyWalshProf/SeleniumAxeDotnet#151]
**Is your feature request related to a problem? Please describe.**
Our site doesn't have a need to scan our iframes. We've built some logic to manually remove them from the DOM, but that's likely causing instability resulting in an inconsistent unhandled JS exception. It's possible (and maybe even likely) that we've caused the instability with our adjustments, but we **really** wanted to find a way around the script injection. In addition to this, the `FindElements` call is adding significant latency to our tests, which is something we'd like to avoid.

OpenQA.Selenium.WebDriverException : unknown error: Cannot read property 'charAt' of undefined
  (Session info: headless chrome=90.0.4430.93)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.17763 x86_64)
at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary\`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.ExecuteScriptCommand(String script, String commandName, Object[] args)
   at Selenium.Axe.WebDriverInjectorExtensions.InjectIntoFrames(IWebDriver driver, String script, IList\`1 parents)
   at Selenium.Axe.WebDriverInjectorExtensions.Inject(IWebDriver driver, IAxeScriptProvider scriptProvider)

**Describe the solution you'd like**
Make [this line](https://github.com/TroyWalshProf/SeleniumAxeDotnet/blob/744a802ddade46f45a81edbb50bdedd231d5e93a/Selenium.Axe/Selenium.Axe/WebDriverInjectorExtensions.cs#L24) optional via config so we can turn off the injection when we don't need it.

**Describe alternatives you've considered**
See above. When trying to manually remove iframes, we're likely causing exceptions for ourselves.

[Related question](https://github.com/SeleniumHQ/htmlunit-driver/issues/65)
Perhaps we need to upgrade to a newer version? We're currently on (the admittedly old) 1.5.2.

**Additional context**
 - OS: Windows NT
 - Browser: Chrome (headless)
 - Version: 90.0.4430.93

**Comment by TroyWalshProf** [comment]
Fixed
