### ISSUE TITLE
Deque .NET bindings upgrade instructions

### ISSUE THREAD

**Issue by Piedone** [TroyWalshProf/SeleniumAxeDotnet#334]
**Is your feature request related to a problem? Please describe.**
We'd like to migrate to Deque' .NET bindings. Instructions on what to do would be great. However, I'm not actually sure how active that project is.

**Describe the solution you'd like**
What's mentioned under https://github.com/TroyWalshProf/SeleniumAxeDotnet#what-will-be-happening

**Describe alternatives you've considered**
The alternative is not migrating yet :).

**Comment by TroyWalshProf** [comment]
This project is in maintenance mode until Deque Axe Core gets out of alpha and https://github.com/microsoft/html-reporter-for-axe-core-dotnet gets released to Nuget.org.

Once those two things happen, we will document the upgrade/migration instructions.

**Comment by Piedone** [comment]
I see, thank you.

**Comment by Piedone** [comment]
Related `Deque.AxeCore.Selenium` issue about the NuGet release: https://github.com/dequelabs/axe-core-nuget/issues/84. And the one for the `AxeCore.HTMLReporter.Selenium` NuGet release: https://github.com/microsoft/html-reporter-for-axe-core-dotnet/issues/46

**Comment by Piedone** [comment]
Deque.AxeCore.Selenium is now released.

**Comment by Piedone** [comment]
Maybe now the recommended migration path should rather be to SeleniumAxeHtmlDotnet?

**Comment by TroyWalshProf** [comment]
> Maybe now the recommended migration path should rather be to SeleniumAxeHtmlDotnet?

Yes, that is the path forward as it does not look like the MS reporter is getting any love.

**Comment by Piedone** [comment]
Great!
