### ISSUE TITLE
Option to generate html report with violations only

### ISSUE THREAD

**Issue by 1nfected** [TroyWalshProf/SeleniumAxeDotnet#84]
I'm trying to figure out how to generate an html report with violations only.

Is there a way to do that currently? If not, would it be possible add such a feature?

**Comment by TroyWalshProf** [comment]
I have been thinking of adding that for a while. - Consider it added to the backlog.

*Currently there is no good way to filter out the unwanted types.
That being said you can limit the number of those results coming back by using the result type option.  
See: https://www.deque.com/axe/core-documentation/api-documentation/#options-parameter sub item 6.

**Comment by TroyWalshProf** [comment]
@1nfected a developer is working on this right now:
https://github.com/TroyWalshProf/SeleniumAxeDotnet/pull/113

**Comment by TroyWalshProf** [comment]
This feature has been added to:
https://www.nuget.org/packages/Selenium.Axe/2.0.2

https://troywalshprof.github.io/SeleniumAxeDotnet/#/?id=creating-a-html-report
See: _Report with only violations and passes_ example

**Comment by 1nfected** [comment]
This is great. Will try this out soon.

Thanks!
